### ISSUE TITLE
Deployed app on heroku delay loaded css

### ISSUE THREAD

**Issue by salahatwa** [ganatan/angular9-app#5]
Dear gentle ,

 i deployed your app on heroku  but i see css delayed on load

kindly find deployed URL
https://tyolk.herokuapp.com/

![image](https://user-images.githubusercontent.com/11550708/79967546-a4523300-8497-11ea-8ddf-d1a7734390b6.png)

**Comment by ganatan** [comment]
@salahatwa 

Hi,
this type of error appears with an incorrect basehref.

For example
with the repo

- https://github.com/ganatan/angular-example-starter

If I use the script ng build
I serve the application like this
https://your-domain.com

If I use the script ng build --base-href=/angular-example-starter/
I serve the application  like this
https://your-domain.com/angular-example-starter


With the repo
- https://github.com/ganatan/angular9-app

I have two scripts
1/ "build:ssr": "ng build --prod && ng run angular-starter:server:production",
2/ "build-demo:ssr": "ng build --prod --base-href=/angular-webapp/ && ng run angular-starter:server:production",

I serve the application like this
1/ https://angular.ganatan.com
2/ https://demo.ganatan.com/angular-webapp/

I don't know Heroku but you have to adapt your baseref

I hope it will help

**Comment by salahatwa** [comment]
Thanks alot for your support , you are very helpful

**Comment by ganatan** [comment]
My pleasure!
Mi casa es su casa

And if you like you can star
